### ISSUE TITLE
cli shebang fails on linux due to varying env features

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/migrator#1]
macos the shebang we are using to run node with arguments works OK, but on linux it fails because `/usr/bin/env` doesn't handle parsing on whitespace and running an executable with command line arguments.

```
./node_modules/.bin/migrator migrate                                              
/usr/bin/env: 'node --no-warnings --experimental-modules --experimental-json-modules': No such file or directory
```

This is discussed a bunch on [stackoverflow](https://unix.stackexchange.com/questions/63979/shebang-line-with-usr-bin-env-command-argument-fails-on-linux). I think we'll need to write a wrapper script with a regular shebang that `exec`s node with arguments.

**Comment by focusaurus** [comment]
To workaround you should be able to run the command this way:

```sh
node --no-warnings --experimental-modules --experimental-json-modules ./node_modules/.bin/migrator migrate
```

**Comment by aldeed** [comment]
@focusaurus PR with potential fix: https://github.com/reactioncommerce/migrator/pull/2

I don't have my linux laptop with me, so I haven't tested it but it works the same on Mac.
